# Generated by Django 3.1.3 on 2021-03-14 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
                ('item_name', models.CharField(max_length=200)),
                ('item_description', models.CharField(max_length=10000)),
                ('founder_name', models.CharField(max_length=200)),
                ('founder_number', models.CharField(max_length=200)),
            ],
        ),
    ]
